### ISSUE TITLE
I found 2 problems at once

### ISSUE THREAD

**Issue by Willem07** [Pandarix/Beautify#16]
**The first problem**

When you put blinds of different types, then you open them, then the rest turn into the blinds that I opened first
![2023-10-02_17 12 25](https://github.com/Pandarix/Beautify/assets/51959206/72e45b1e-3c24-4107-8190-f9ef079a07fd)
![2023-10-02_17 12 36](https://github.com/Pandarix/Beautify/assets/51959206/94e7105c-6e52-462f-a2c8-624b30939ed9)
![2023-10-02_17 12 48](https://github.com/Pandarix/Beautify/assets/51959206/863b41a1-657b-4db5-adfc-eab1e964710c)

**The second problem is the translation of some items**

Some items that I translate into another language break the description
![2023-10-02_17 13 28](https://github.com/Pandarix/Beautify/assets/51959206/cead3ad7-377b-4445-b6df-430e91c4d74a)
![2023-10-02_17 13 43](https://github.com/Pandarix/Beautify/assets/51959206/df2b7630-7a91-4c8a-90cf-8d6b70570b9b)

When an item has an English name, the description works correctly
![2023-10-02_17 13 17](https://github.com/Pandarix/Beautify/assets/51959206/2fff4ddd-18b3-4069-b47c-c7c846662e86)

Some items work correctly with the name and description, and some do not
![2023-10-02_17 21 06](https://github.com/Pandarix/Beautify/assets/51959206/eb168c0c-0ee0-4b9b-b5b5-832bb2d33e2c)

forge 1.20.1
beautify-2.0.1

You can try a new translation
[Beautify](https://github.com/Willem07/translation-Beautify-mod)

**Comment by Willem07** [comment]
[I would also like to backport fixes as in the fabric version](https://legacy.curseforge.com/minecraft/mc-mods/beautify-refabricated/files/4775399)

**Comment by Pandarix** [comment]
**Thank you for reporting these issues and especially the translation!**

<hr>

> When you put blinds of different types, then you open them, then the rest turn into the blinds that I opened first

The Blinds-Bug was actually an error that resulted from the rework of the structure of the mod. Previously, because I was inexperienced, I created classes for every blind-type. After the rework, there was only one base-class. That however broke the `sameBlindType` check that was comparing classes instead of instances.

- `sameBlindType` now compares 2 instances instead of the class to itself

<hr>

> Some items that I translate into another language break the description
> When an item has an English name, the description works correctly
> Some items work correctly with the name and description, and some do not

The language keys were composed of the Item's name and a suffix. I haven't thought of the issue that Item's names would also change between languages instead of representing the internal names.

- Language Keys in `appendHoverText` are now hard-coded to prevent this issue

<hr>

> You can try a new translation

Thank you, I've added the `ru_ru.json` to the fix I'll be pushing soon.
Once I've fixed enough, I'll credit you in the changelogs. If I don't remember, please remind be :)

- Added `ru_ru.json` to the `lang` folder

<hr>

> I would also like to backport fixes as in the fabric version

Also, I'll take a look at the fixes for fabric asap!

**Comment by Willem07** [comment]
I have corrected some names, in future updates you can overwrite it.
[update lang](https://github.com/Willem07/translation-Beautify-mod/blob/0d072c2c1406fcb5b1d075b0c6978ebf72b7d907/ru_ru.json)
