### ISSUE TITLE
[Feature Request] Unify or Disable Ropes

### ISSUE THREAD

**Issue by AStrangeMouse** [Pandarix/Beautify#2]
Would it be possible to add support for Quark ropes? Or to have a config option allowing us to disable the ropes this mod adds outright?

I love these models, but I already have 3 - 4 mods each adding their own rope.

Sorry if I'm doing this wrong, I have no idea how to use GitHub. :'D

**Comment by Pandarix** [comment]
If you have issues regarding the recipe, I suggest using ["Polymorph"](https://www.curseforge.com/minecraft/mc-mods/polymorph/files)
Sadly, there is no 1.19. Version support available for this mod at this moment in time.

Could you describe what exactly the problem is you're experiencing?
If it is the recipe, I should be able to make a config option for that :).

**Comment by Pandarix** [comment]
No further answer recieved
