### ISSUE TITLE
Beautify Crashing server 

### ISSUE THREAD

**Issue by Zelioth** [Pandarix/Beautify#9]
MC 1.19.2 forge 43.1.34. randomly crashing server and it gave the crash report referencing beautify 

[crash-2022-10-11_00.10.19-server.txt](https://github.com/Pandarix/Beautify/files/9758023/crash-2022-10-11_00.10.19-server.txt)

**Comment by Pandarix** [comment]
I think that the error you're getting is caused by another problem. It says:
`"java.lang.NoSuchMethodError: 'boolean com.github.Pandarix.beautify.util.KeyBoardHelper.isHoldingShift()'"`
but when the mod is loaded correctly which evidently isn't the case:
`{re:classloading}`,
the method should be there and visible for the compiler.

Here you can see the class that contains the method:
![image](https://user-images.githubusercontent.com/98489042/195203481-ec9085e2-53ff-4747-9ccd-aef687f78fee.png)

Also, I noticed that the log says that a ton of mods you're using are "incompatible".
![image](https://user-images.githubusercontent.com/98489042/195204213-a1793cd9-69e7-4546-b5ad-17771f2757f5.png)

Does your modpack work without my mod in it?

**Comment by Zelioth** [comment]
Yes, the modpack runs what seems to be fine with or without the mod. I am unsure why they say imcompatible when they are running to my knowledge fine. I haven't seen any of those in the profilers or java heap reports. I wonder what exactly it's referencing as imcompatible. like with another mod or with forge?

**Comment by Pandarix** [comment]
This seems to be a reocurring issue, I'll look into this asap!

**Comment by Zelioth** [comment]
Could it be because I am on the newest version of forge and the mods haven't been updated to "support" the newest forge

**Comment by Pandarix** [comment]
Whatever may be the case, i've updated the Forge version of the mod and have replaced the ShiftKeyDown thing with a new and easier System I wasn't quite aware of. I'll send the link once the file is done with review on CurseForge.

**Comment by Pandarix** [comment]
https://www.curseforge.com/minecraft/mc-mods/beautify-decorate/files/4026110
please try this and tell me if it works

**Comment by Pandarix** [comment]
any update?
